version: '3.8'

services:
  db:
    container_name: postgres-db
    image: io.nbompetsis/postgres:latest
    build:
      context: ./postgres-build
      args:
        POSTGRES_TAG: "${postgres_tag}"
        DATABASE_NAME: "${postgres_service_db}"
        DATABASE_USER: "${postgres_service_user}"
        DATABASE_USER_PASSWORD: "${postgres_service_user_pass}"
    ports:
      - "${postgres_port}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${postgres_default_db}"
      POSTGRES_USER: "${postgres_super_user}"
      POSTGRES_PASSWORD: "${postgres_super_user_pass}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "--dbname=${postgres_service_db}"
        ]
      interval: 30s
      timeout: 30s
      retries: 5

  pgadmin:
    container_name: pgadmin-ui
    image: "dpage/pgadmin4:${pgadmin_tag}"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${pgadmin_email}"
      PGADMIN_DEFAULT_PASSWORD: "${pgadmin_email_pass}"
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
