version: '3.8'

services:
  db:
    container_name: postgres-db
    image: io.nbompetsis/postgres:latest
    build:
      context: ./
      dockerfile: ./postgres_image/Dockerfile
      args:
        DATABASE_NAME: service_db
        DATABASE_USER: service-user
        DATABASE_USER_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    container_name: pgadmin-ui
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - db
